Lab2N3/Lab2N3/Models/Order.cs
using System;
using System.Collections.Generic;

namespace Lab2N3.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public string? CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        public decimal? Freight { get; set; }
        public string? ShipName { get; set; }
        public string? ShipAddress { get; set; }
        public string? ShipCity { get; set; }
        public string? ShipRegion { get; set; }
        public string? ShipPostalCode { get; set; }
        public string? ShipCountry { get; set; }

        public virtual Customer? Customer { get; set; }
        public virtual Employee? Employee { get; set; }
        public virtual Shipper? ShipViaNavigation { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Lab2N3/Lab2N3/Models/OrderDetail.cs
using System;
using System.Collections.Generic;

namespace Lab2N3.Models
{
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }

        public virtual Order Order { get; set; } = null!;
        public virtual Product Product { get; set; } = null!;
    }
}

Lab2N3/Lab2N3/Pages/Cart.cshtml.cs
using Lab2N3.Logics;
using Lab2N3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace Lab2N3.Pages
{
	public class CartModel : PageModel
	{
		private NorthwindContext context;
		private IHttpContextAccessor httpContextAccessor;
		public Dictionary<Product, int> Cart { get; set; } = null!;
		public decimal CartTotal { get; set; }

		public List<Models.Employee> Employees { get; set; }
		public List<Models.Customer> Customers { get; set; }

		[BindProperty]
		public int? EmployeeID { get; set; }
		[BindProperty]
		public string? CustomerID { get; set; }
		[BindProperty]
		public DateTime? OrderDate { get; set; }
		[BindProperty]
		public string? ShipAddress { get; set; }
		[BindProperty]
		public string? ShipCountry { get; set; }
		[BindProperty]
		public string? Message { get; set; }

		private readonly IHubContext<CartHub> _hubContext;

		public CartModel(NorthwindContext context, IHttpContextAccessor httpContextAccessor, IHubContext<CartHub> hubContext)
		{
			this.context = context;
			_hubContext = hubContext;
			this.httpContextAccessor = httpContextAccessor;
			Cart = new Dictionary<Product, int>();
			CartTotal = 0;

			Employees = context.Employees.ToList();
			Customers = context.Customers.ToList();
		}

		public void OnGet()
		{
			ProcessRequest();
		}

		public async Task OnPostAddToCart(int ProductID)
		{
			CartManager cartManager = new CartManager(httpContextAccessor.HttpContext!.Session);
			cartManager.AddToCart(ProductID);
			ProcessRequest();
			await _hubContext.Clients.All.SendAsync("UpdateCart", Cart);
		}
		public async Task OnPostRemoveFromCart(int ProductID)
		{
			CartManager cartManager = new CartManager(httpContextAccessor.HttpContext!.Session);
			cartManager.RemoveFromCart(ProductID);
			ProcessRequest();
			await _hubContext.Clients.All.SendAsync("UpdateCart", Cart);
		}

		public void OnPostOrderNow()
		{
			var newOrder = new Order();
			newOrder.EmployeeId = EmployeeID;
			newOrder.CustomerId = CustomerID;
			newOrder.OrderDate = OrderDate;
			newOrder.ShipCountry = ShipCountry;
			newOrder.ShipAddress = ShipAddress;
			Dictionary<int, int> cart = (new CartManager(httpContextAccessor.HttpContext!.Session)).GetProducts();
			List<Product> products = context.Products.ToList();
			foreach (int productId in cart.Keys)
			{
				Product? p = products.FirstOrDefault(item => item.ProductId == productId);
				if (p != null)
				{
					var orderDetail = new OrderDetail()
					{
						ProductId = productId,
						UnitPrice = (decimal)p.UnitPrice,
						Quantity = (short)cart[productId],
					};
					newOrder.OrderDetails.Add(orderDetail);
				}
			}
			context.Orders.Add(newOrder);
			context.SaveChanges();
			Message = $"Add Order Successfully";
			CartManager cartManager = new CartManager(httpContextAccessor.HttpContext!.Session);
			cartManager.RemoveTemporaryCart();
		}

		void ProcessRequest()
		{
			Dictionary<int, int> cart = (new CartManager(httpContextAccessor.HttpContext!.Session)).GetProducts();
			List<Product> products = context.Products.ToList();
			foreach (int productId in cart.Keys)
			{
				Product? p = products.FirstOrDefault(item => item.ProductId == productId);
				CartTotal += (Convert.ToDecimal(p.UnitPrice) * cart[productId]);
				if (p != null)
					Cart.Add(p, cart[productId]);
			}
		}
	}
}

Lab2N3/Lab2N3/Pages/Index.cshtml.cs
using Lab2N3.Logics;
using Lab2N3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Lab2N3.Pages
{
	public class IndexModel : PageModel
	{
		private NorthwindContext context;
		private IHttpContextAccessor httpContextAccessor;

		//cach viet nhanh Constructor: cort tab
		public IndexModel(NorthwindContext context, IHttpContextAccessor httpContextAccessor)
		{
			this.context = context;
			this.httpContextAccessor = httpContextAccessor;
		}
		public List<Models.Product> Products { get; set; }
		public List<Models.Category> Categories { get; set; }
		public List<Models.Supplier> Suppliers { get; set; }

		[BindProperty]
		public int? CategoryID { get; set; }
		[BindProperty]
		public int? SupplierID { get; set; }
		[BindProperty]
		public string SortBy { get; set; }
		[BindProperty(SupportsGet = true)]
		public string key { get; set; }
		public int pageSize = 12;
		public bool isFilter { get; set; }
		public int? TotalPages { get; set; }
		public int CurrentPageNumber { get; set; }
		public int? PreviousPage { get; set; }
		public int? NextPage { get; set; }

		public void OnGet(int? pageNumber)
		{
			isFilter = false;
			int pageNum = (pageNumber ?? 1);
			CurrentPageNumber = pageNum;

			Products = context.Products
				.Include(p => p.Category)
				.Include(p => p.Supplier)
				.ToList();


			int totalProducts = Products.Count();
			TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

			var ProductResult = Products.Skip((pageNum - 1) * pageSize).Take(pageSize);
			Products = ProductResult.ToList();

			Categories = context.Categories.ToList();
			Suppliers = context.Suppliers.ToList();

			SortBy = "ProductNameAZ";
			ProcessPage();
		}

		public void OnPostFilter(int? pageNumber)
		{
			isFilter = true;
			int pageNum = (pageNumber ?? 1);
			CurrentPageNumber = pageNum;
			Categories = context.Categories.ToList();
			Suppliers = context.Suppliers.ToList();

			Products = context.Products
					.Include(p => p.Category)
					.Include(p => p.Supplier)
					.Where(p => CategoryID == -1 || p.CategoryId == CategoryID || CategoryID == null)
					.Where(p => SupplierID == -1 || p.SupplierId == SupplierID || SupplierID == null)
					.ToList();

			List<Product> SearchResult = new List<Product>();
			key = httpContextAccessor.HttpContext.Session.GetString("Key");
			if (key != null)
			{
				foreach (var p in Products)
				{
					if (p.ProductName.ToLower().Contains(key.ToLower()))
					{
						SearchResult.Add(p);
					}
				}
				if (SearchResult != null)
					Products = SearchResult;
			}
			int totalProducts = Products.Count();
			TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

			var ProductsResult = Products.Skip((pageNum - 1) * pageSize).Take(pageSize);
			Products = ProductsResult.ToList();

			switch (SortBy)
			{
				case "ProductNameAZ":
					Products = Products.OrderBy(o => o.ProductName).ToList();
					break;
				case "ProductNameZA":
					Products = Products.OrderByDescending(o => o.ProductName).ToList();
					break;
				case "UnitPriceAZ":
					Products = Products.OrderBy(o => o.UnitPrice).ToList();
					break;
				case "UnitPriceZA":
					Products = Products.OrderByDescending(o => o.UnitPrice).ToList();
					break;
				case "UnitsInStockAZ":
					Products = Products.OrderBy(o => o.UnitsInStock).ToList();
					break;
				case "UnitsInStockZA":
					Products = Products.OrderByDescending(o => o.UnitsInStock).ToList();
					break;
				default:
					break;
			}
			ProcessPage();
		}


		public void OnPostSearch(int? pageNumber)
		{
			httpContextAccessor.HttpContext.Session.SetString("Key", "");
			isFilter = true;
			int pageNum = (pageNumber ?? 1);
			CurrentPageNumber = pageNum;
			Categories = context.Categories.ToList();
			Suppliers = context.Suppliers.ToList();
			Products = context.Products.ToList();

			List<Product> SearchResult = new List<Product>();
			if (key != null)
			{
				httpContextAccessor.HttpContext.Session.SetString("Key", key);
				foreach (var p in Products)
				{
					if (p.ProductName.ToLower().Contains(key.ToLower()))
					{
						SearchResult.Add(p);
					}
				}
				if (SearchResult != null)
					Products = SearchResult;
			}
			int totalProducts = Products.Count();
			TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

			var ProductsResult = Products.Skip((pageNum - 1) * pageSize).Take(pageSize);
			Products = ProductsResult.ToList();

			if (SortBy == null)
			{
				SortBy = "ProductNameAZ";
			}
		}

		public void OnPostAddToCart(int ProductID)
		{
			GetData();
			CartManager cartManager = new CartManager(httpContextAccessor.HttpContext!.Session);
			cartManager.AddToCart(ProductID);
		}

		private void GetData()
		{
			Categories = context.Categories.ToList();
			Suppliers = context.Suppliers.ToList();
			Products = context.Products.ToList();
		}

		void ProcessPage()
		{
			PreviousPage = CurrentPageNumber - 1;
			NextPage = CurrentPageNumber + 1;
			if (PreviousPage <= 1)
				PreviousPage = 1;
			if (NextPage >= TotalPages)
				NextPage = TotalPages;
		}

	}
}

Lab2N3/Lab2N3/Pages/Order.cshtml.cs
using Lab2N3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Lab2N3.Pages
{
	public class OrderModel : PageModel
	{
		private readonly NorthwindContext context;

		public OrderModel(NorthwindContext context)
		{
			this.context = context;
		}

		public List<Models.Order> Orders { get; set; }
		public List<Models.Employee> Employees { get; set; }
		public List<Models.Customer> Customers { get; set; }
		#region

		[BindProperty]
		public int? EmployeeID { get; set; }
		[BindProperty]
		public string? CustomerID { get; set; }
		[BindProperty]
		public DateTime? FromDate { get; set; }
		[BindProperty]
		public DateTime? ToDate { get; set; }
		[BindProperty]
		public string SortBy { get; set; }
		[BindProperty]
		public string? Message { get; set; }
		#endregion
		public bool isFilter { get; set; }
		public int? TotalPages { get; set; }
		public int pageSize = 42;
		public int CurrentPageNumber { get; set; }
		public void OnGet(int? pageNumber)
		{
			int pageNum = (pageNumber ?? 1);
			CurrentPageNumber = pageNum;
			isFilter = false;
			Orders = context.Orders
				.Include(c => c.Customer)
				.Include(e => e.Employee)
				.ToList();
			// Calculate the total number of pages
			int totalOrders = Orders.Count();
			TotalPages = (int)Math.Ceiling((double)totalOrders / pageSize);

			var OrdersResult = Orders.Skip((pageNum - 1) * pageSize).Take(pageSize);
			Orders = OrdersResult.ToList();

			Customers = context.Customers.ToList();
			Employees = context.Employees.ToList();
		}

		public void OnGetAdd()
		{
			RedirectToPage("/Add");
		}

		public void OnPostFilter(int? pageNumber)
		{
			isFilter = true;
			int pageNum = (pageNumber ?? 1);
			CurrentPageNumber = pageNum;
			Customers = context.Customers.ToList();
			Employees = context.Employees.ToList();

			Orders = context.Orders
				.Include(c => c.Customer)
				.Include(e => e.Employee)
				.Where(e => EmployeeID == -1 || e.EmployeeId == EmployeeID)
				.Where(e => CustomerID == "-1" || e.CustomerId == CustomerID)
				.Where(e => e.OrderDate >= FromDate && e.OrderDate <= ToDate)
				.ToList();
			// Calculate the total number of pages
			int totalOrders = Orders.Count();
			TotalPages = (int)Math.Ceiling((double)totalOrders / pageSize);

			var OrdersResult = Orders.Skip((pageNum - 1) * pageSize).Take(pageSize);
			Orders = OrdersResult.ToList();
			switch (SortBy)
			{
				case "OrderDate":
					Orders = Orders.OrderByDescending(o => o.OrderDate).ToList();
					break;
				case "Freight":
					Orders = Orders.OrderBy(o => o.Freight).ToList();
					break;
				default:
					break;
			}
		}
	}
}

Lab2N3/Lab2N3/Pages/OrderDetail.cshtml.cs
using Lab2N3.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Lab2N3.Pages
{
	public class OrderDetailModel : PageModel
	{
		private readonly NorthwindContext context;

		public OrderDetailModel(NorthwindContext context)
		{
			this.context = context;
		}

		public List<Models.OrderDetail> OrderDetails { get; set; }

		public void OnGet(int OrderID)
		{
			OrderDetails = context.OrderDetails
				.Include(od => od.Product)
				.Where(od => od.OrderId == OrderID)
				.ToList();
		}
	}
}

Lab2N3/Lab2N3/Pages/Cart.cshtml
@page
@using Lab2N3.Models
@model Lab2N3.Pages.CartModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
	int index = 0;
}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Cart</title>
	<link rel="stylesheet" href="assets/css/styles.css">
	<link rel="stylesheet"
		  href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
</head>

<body>
	<header>
		<a href="/Index" class="logo"><h2>Lab2n3/PRN221</h2></a>
		@* <form class="search-form" onsubmit="return validate()" method="post">
			<div class="wrap">
				<div class="search">
					<input type="text" title="Cannot search in view cart page" disabled class="searchTerm" placeholder="What are you looking for?">
					<button type="submit" disabled class="searchButton" title="Cannot search in view cart page">
						<i class="fa fa-search"></i>
					</button>
				</div>
			</div>
		</form> *@
		<ul class="top-menu">
			<li><a title="Home" href="/Index"><i class="fa fa-home"></i></a></li>
			<li><a title="View cart" href="/Cart" class="active"><i class="fa fa-shopping-cart"></i></a></li>
			<li><a title="Orders" href="/Order"><i class="fa fa-file-alt"></i></a></li>
		</ul>
	</header>
	<main class="cart-main">
		<section class="cart-order" style="min-height: 81vh;">
			<table class="cart-order-table" border="1px" style="border-collapse: collapse;">
				<thead>
					<tr class="table-header">
						<th>No.</th>
						<th>Product Name</th>
						<th style="text-align: center;">Price</th>
						<th style="text-align: center;">Quantity</th>
						<th style="text-align: center;">Amount</th>
					</tr>
				</thead>
				<tbody>
					@if (Model.Cart == null || Model.Cart.Count == 0)
					{
						if (Model.Message == null)
						{
							<tr class="table-body">
								<td colspan="5" style="text-align: center; padding: 10px">
									<a>There are currently no products in the cart</a><br><br>
									<a>(Try going</a> <a href="../"> Back to home page </a> <a> and adding a few products)</a>
								</td>
							</tr>
						}
						else
						{
							<tr class="table-body">
								<td colspan="5" style="text-align: center; padding: 10px;">
									<img src="~/images/circlecheck.png" height="80"/><br></br>
									<a style="text-decoration: none; color: green" href="/Order">@Model.Message</a>
									<br><br>
									<a href="../">(Going to home page </a> <a> and continue shopping)</a>
								</td>
							</tr>
						}
					}
					else
						@foreach (Product p in Model.Cart.Keys)
						{
							{ index++; }
							<tr class="table-body">
								<td style="text-align: center;">@index</td>
								<td>@p.ProductName</td>
								<td style="text-align: center;">$@p.UnitPrice?.ToString("0.00")</td>
								<td class="cart-quantity">
									<form style="margin: 0" method="post">
										<button type="submit" asp-page-handler="removefromcart" class="fa fa-minus btn-quantity" name="ProductID" value="@p.ProductId">
										</button>
									</form>
									<p>@Model.Cart[p]</p>
									<form style="margin: 0" method="post">
										<button type="submit" asp-page-handler="addtocart" class="fa fa-plus btn-quantity" name="ProductID" value="@p.ProductId">
										</button>
									</form>
								</td>
								<td style="text-align: center;">$@((p.UnitPrice * @Model.Cart[p])?.ToString("0.00"))</td>
							</tr>
						}
				</tbody>

				<tfoot class="table-foot">
					<tr>
						<td colspan="5" class="total-cart">
							Total: $@Model.CartTotal.ToString("0.00")
						</td>
					</tr>
					<tr>
						<td colspan="5">
							<button class="btn-order" id="btn-show-form">
								Order now
							</button>
						</td>
					</tr>
				</tfoot>
			</table>
		</section>
	</main>
	<div id="formPopup" style="display: none; color: black">
		<form style="margin: 0" method="post">
			<fieldset>
				<legend><b>Information of Order</b></legend>
				<label>Employee:</label>
				<select name="EmployeeID">
					@if (Model.Employees != null)
					{
						foreach (var e in Model.Employees)
						{
							<option value="@e.EmployeeId">@e.FirstName @e.LastName</option>
						}
					}
				</select>
				<br>
				<br>
				<label>Customer:</label>
				<select name="CustomerID">
					@if (Model.Customers != null)
					{
						foreach (var e in Model.Customers)
						{
							<option value="@e.CustomerId">@e.CompanyName - @e.ContactName</option>
						}
					}
				</select>
				<br>
				<br>
				<label>Order Date:</label>
				<input type="date" style="width: 100%; height: 25px" id="OrderDate" value="@DateTime.Today.ToString("yyyy-MM-dd")" name="OrderDate">
				<br>
				<br>
				<label>Ship Address:</label>
				<input type="text" style="width: 100%; height: 25px" id="ShipAddress" name="ShipAddress" placeholder="FPT University - Hoa Lac High Tech Park, Hanoi, Vietnam">
				<br>
				<br>
				<label>Ship Country:</label>
				<input type="text" style="width: 100%; height: 25px" id="ship_country" maxlength="15" name="ShipCountry" placeholder="Vietnam">
				<br>
				<br>
			</fieldset>
			<div style="display: flex; justify-content: space-between; margin-top: 10px">
				<div>
					<input style="width: fit-content; margin: 10px 0 0 10px;" class="btn-close" type="button" id="btn-close-form" value="Close">
				</div>
				<div>

					<input style=" width: fit-content; margin: 10px 10px 0 0;" class="btn-order" asp-page-handler="ordernow" type="submit" value="Order">
				</div>
			</div>
		</form>
	</div>
	<script>
		const btn = document.getElementById("btn-show-form");
		btn.addEventListener('click', () => {
			const form = document.getElementById('formPopup');
			if (form.style.display == 'none') {
				form.style.display = 'block';
			} else {
				form.style.display = 'none';
			}
		});

		const btnClose = document.getElementById("btn-close-form");
		btnClose.addEventListener('click', () => {
			const form = document.getElementById('formPopup');
			form.style.display = 'none';
		});
	</script>
	<script src="/microsoft-signalr/signalr.js"></script>
	<script src="/assets/js/realtime.js"></script>
</body>
<footer>
	<section class="footer" style="position: relative; margin-top: 1em;">
		<p>Copyright © @DateTime.Now.Year Nguyen Luong Khang (HE161660) PRN221</p>
	</section>
</footer>

Lab2N3/Lab2N3/Pages/Order.cshtml
@page "{pageNumber?}"
@model Lab2N3.Pages.OrderModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Order</title>
	<link rel="stylesheet" href="/assets/css/styles.css">
	<link rel="stylesheet"
		  href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
	<style>
		.orderList th, td {
			padding: 2px 5px;
		}
	</style>
</head>

<body>
	<header>
		<a href="/Index" class="logo"><h2>Lab2n3/PRN221</h2></a>
		@* <form class="search-form" onsubmit="return validate()" method="post">
		<div class="wrap">
		<div class="search">
		<input type="text" title="Cannot search in view cart page" disabled class="searchTerm" placeholder="What are you looking for?">
		<button type="submit" disabled class="searchButton" title="Cannot search in view cart page">
		<i class="fa fa-search"></i>
		</button>
		</div>
		</div>
		</form> *@
		<ul class="top-menu">
			<li><a title="Home" href="/Index"><i class="fa fa-home"></i></a></li>
			<li><a title="View cart" href="/Cart"><i class="fa fa-shopping-cart"></i></a></li>
			<li><a title="Orders" href="/Order" class="active"><i class="fa fa-file-alt"></i></a></li>
		</ul>
	</header>
	<main style="min-height: 81vh;">
		<div class="filter">
			<form method="post" asp-page-handler="Filter" id="form">
				<h3>Employee:</h3>
				<select name="EmployeeID" asp-for="EmployeeID"
						style="width: 100%; height: 30px">
					<option value="-1">All Employees</option>
					@if (Model.Employees != null)
					{
						foreach (var e in Model.Employees)
						{
							<option value="@e.EmployeeId">@e.FirstName @e.LastName</option>
						}
					}
				</select>
				<h3>Customer:</h3>
				<select name="CustomerID" asp-for="CustomerID"
						style="width: 100%; height: 30px">
					<option value="-1">All Customers</option>
					@if (Model.Customers != null)
					{
						foreach (var e in Model.Customers)
						{
							<option value="@e.CustomerId">@e.CompanyName</option>
						}
					}
				</select>
				<h3>From:</h3>
				<input type="date" name="FromDate" value="1980-01-01" style="width: 100%; height: 30px" />
				<h3>To:</h3>
				<input type="date" name="ToDate" value="@DateTime.Today.ToString("yyyy-MM-dd")" style="width: 100%; height: 30px" />
				<h3>Sort By:</h3>
				@switch (Model.SortBy)
				{
					case "OrderDate":
						<input type="radio" checked value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
					case "Freight":
						<input type="radio" value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" checked value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
					default:
						<input type="radio" checked value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
				}
				<input type="hidden" id="pageNumber" name="pageNumber">
				<input type="submit" value="Load Orders" class="btn-apply-filter" />
			</form>
		</div>
		<div class="container">
			<div class="row">
				@if (Model.Orders.Count != 0)
				{
					<table class="orderList" border="1px" style="border-collapse:collapse">
						<tr>
							<th>OrderID</th>
							<th>Customer</th>
							<th>Employee</th>
							<th>Order Date</th>
							<th>Required Date</th>
							<th>Shipped Date</th>
							<th>Freight</th>
							<th>Ship Country</th>
						</tr>
						@foreach (var o in Model.Orders)
						{
							<tr>
									<td>
										<a href="/OrderDetail/@o.OrderId">@o.OrderId</a>
									</td>
								<td>@o.Customer.CompanyName</td>
								<td>@o.Employee.FirstName @o.Employee.LastName</td>
								<td>@o.OrderDate?.ToString("MM-dd-yyyy")</td>
								<td>@o.RequiredDate?.ToString("MM-dd-yyyy")</td>
								<td>@o.ShippedDate?.ToString("MM-dd-yyyy")</td>
								<td>@o.Freight</td>
								<td>@o.ShipCountry</td>
							</tr>
						}
					</table>
				}
			</div>
			@if (Model.TotalPages >= 1)
			{
				<div class="pagination-container">
					<div class="pagination">
						@for (int i = 1; i <= Model.TotalPages; i++)
						{
							@if (!Model.isFilter)
							{
								@if (Model.CurrentPageNumber == i)
								{
									<a class="active" href="/Order/@i">@i</a>
								}
								else
								{
									<a href="/Order/@i">@i</a>
								}
							}
							else
							{
								@if (Model.CurrentPageNumber == i)
								{
									<a class="active" onclick="OnClickPageNumberLink(@i)" id="pageNumberLink">@i</a>
								}
								else
								{
									<a onclick="OnClickPageNumberLink(@i)" id="pageNumberLink">@i</a>
								}
							}
						}
					</div>
				</div>
			}
			else
			{
				<div style="display: flex; justify-content: center; width: 100%">
					<div>
						<h3> -- No orders match, try another filter --</h3>
					</div>
				</div>
			}
		</div>
	</main>
	<script>
		function OnClickPageNumberLink(i) {
			console.log("pageNumber = " + i);
			document.getElementById('pageNumber').value = i;
			document.getElementById('form').submit();
		}
	</script>
</body>

<footer>
	<section class="footer" style="position: relative; margin-top: 1em;">
		<p>Copyright © @DateTime.Now.Year Nguyen Luong Khang (HE161660) PRN221</p>
	</section>
</footer>