ExerciseRazerPage/ExerciseRazerPage/Models/Order.cs
using System;
using System.Collections.Generic;

namespace ExerciseRazerPage.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public string? CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        public decimal? Freight { get; set; }
        public string? ShipName { get; set; }
        public string? ShipAddress { get; set; }
        public string? ShipCity { get; set; }
        public string? ShipRegion { get; set; }
        public string? ShipPostalCode { get; set; }
        public string? ShipCountry { get; set; }

        public virtual Customer? Customer { get; set; }
        public virtual Employee? Employee { get; set; }
        public virtual Shipper? ShipViaNavigation { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

ExerciseRazerPage/ExerciseRazerPage/Pages/Employee/List.cshtml.cs
using ExerciseRazerPage.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExerciseRazerPage.Pages.Employee
{
	public class ListModel : PageModel
	{
		private readonly NorthwindContext _context;
		public ListModel(NorthwindContext context)
		{
			_context = context;
		}
		public List<Models.Employee> employees { get; set; }
		public void OnGet()
		{
			employees = _context.Employees.ToList();
		}
	}
}

ExerciseRazerPage/ExerciseRazerPage/Pages/Order/Add.cshtml.cs
using ExerciseRazerPage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExerciseRazerPage.Pages.Order
{
    public class AddModel : PageModel
    {
        private readonly NorthwindContext _context;

        public AddModel(NorthwindContext context)
        {
            _context = context;
        }
        public List<Models.Employee> employees { get; set; }
        public List<Models.Customer> customers { get; set; }
        #region
        [BindProperty]
        public int? EmployeeID { get; set; }
        [BindProperty]
        public string? CustomerID { get; set; }
        [BindProperty]
        public DateTime? OrderDate { get; set; }
        [BindProperty]
        public string? ShipAddress { get; set; }
        [BindProperty]
        public string? ShipCountry { get; set; }
        [BindProperty]
        public string? Message { get; set; }
        #endregion
        public void OnGet()
        {
            customers = _context.Customers.ToList();
            employees = _context.Employees.ToList();
        }

        public void OnPost()
        {
            Models.Order o = new Models.Order();
            o.EmployeeId = EmployeeID;
            o.CustomerId = CustomerID;
            o.OrderDate = OrderDate;
            o.ShipCountry = ShipCountry;
            o.ShipAddress = ShipAddress;
            _context.Orders.Add(o);
            _context.SaveChanges();
            Message = $"Add Order Successfully";
        }
    }
}

ExerciseRazerPage/ExerciseRazerPage/Pages/Order/List.cshtml.cs
using ExerciseRazerPage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ExerciseRazerPage.Pages.Order
{
    public class ListModel : PageModel
    {
        private readonly NorthwindContext _context;

        public ListModel(NorthwindContext context)
        {
            _context = context;
        }
        public List<Models.Order> Orders { get; set; }
        public List<Models.Employee> employees { get; set; }
        public List<Models.Customer> customers { get; set; }
        #region
        [BindProperty]
        public int? EmployeeID { get; set; }
        [BindProperty]
        public string? CustomerID { get; set; }
        [BindProperty]
        public DateTime? FromDate { get; set; }
        [BindProperty]
        public DateTime? ToDate { get; set; }
        [BindProperty]
        public string SortBy { get; set; }
        [BindProperty]
        public string? Message { get; set; }
        #endregion
        public bool isFilter { get; set; }
        public int? TotalPages { get; set; }
        public int pageSize = 20;
        public int CurrentPageNumber { get; set; }
        public void OnGet(int? pageNumber)
        {
            int pageNum = (pageNumber ?? 1);
            CurrentPageNumber = pageNum;
            isFilter = false;
            Orders = _context.Orders
                .Include(c => c.Customer)
                .Include(e => e.Employee)
                .ToList();
            // Calculate the total number of pages
            int totalOrders = Orders.Count();
            TotalPages = (int)Math.Ceiling((double)totalOrders / pageSize);

            var OrdersResult = Orders.Skip((pageNum - 1) * pageSize).Take(pageSize);
            Orders = OrdersResult.ToList();

            customers = _context.Customers.ToList();
            employees = _context.Employees.ToList();
        }

        public void OnGetAdd()
        {
            RedirectToPage("/Add");
        }

        public void OnPost(int? pageNumber)
        {
            isFilter = true;
            int pageNum = (pageNumber ?? 1);
            CurrentPageNumber = pageNum;
            customers = _context.Customers.ToList();
            employees = _context.Employees.ToList();

            Orders = _context.Orders
                .Include(c => c.Customer)
                .Include(e => e.Employee)
                .Where(e => EmployeeID == -1 || e.EmployeeId == EmployeeID)
                .Where(e => CustomerID == "-1" || e.CustomerId == CustomerID)
                .Where(e => e.OrderDate >= FromDate && e.OrderDate <= ToDate)
                .ToList();
            // Calculate the total number of pages
            int totalOrders = Orders.Count();
            TotalPages = (int)Math.Ceiling((double)totalOrders / pageSize);

            var OrdersResult = Orders.Skip((pageNum - 1) * pageSize).Take(pageSize);
            Orders = OrdersResult.ToList();
            switch (SortBy)
            {
                case "OrderDate":
                    Orders = Orders.OrderBy(o => o.OrderDate).ToList();
                    break;
                case "Freight":
                    Orders = Orders.OrderBy(o => o.Freight).ToList();
                    break;
                default:
                    break;
            }
        }
    }
}

ExerciseRazerPage/ExerciseRazerPage/Pages/Order/Add.cshtml
@page
@model ExerciseRazerPage.Pages.Order.AddModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
	<style>
		body {
			font-family: Arial, sans-serif;
		}

		label {
			margin: 5px;
		}

		input, select {
			width: 50%;
			height: 30px;
		}
	</style>
</head>
<body>
	<div style="display: flex; justify-content: center">
		<div style="width: 60%; margin-top: 3em">
			<form method="post">
				<fieldset>
					<legend><b>Information of Order</b></legend>
					<label>Employee:</label>
					<select name="EmployeeID">
						@if (Model.employees != null)
						{
							foreach (var e in Model.employees)
							{
								<option value="@e.EmployeeId">@e.FirstName @e.LastName</option>
							}
						}
					</select>
					<br>
					<br>
					<label>Customer:</label>
					<select name="CustomerID">
						@if(Model.customers != null){
						foreach (var e in Model.customers)
						{
							<option value="@e.CustomerId">@e.CompanyName - @e.ContactName</option>
							}
						}
					</select>
					<br>
					<br>
					<label>Order Date:</label>
					<input type="date" id="OrderDate" value="@DateTime.Today.ToString("yyyy-MM-dd")" name="OrderDate">
					<br>
					<br>
					<label>Ship Address:</label>
					<input type="text" id="ShipAddress" name="ShipAddress" placeholder="FPT University - Hoa Lac High Tech Park, Hanoi, Vietnam">
					<br>
					<br>
					<label>Ship Country:</label>
					<input type="text" id="ship_country" maxlength="15" name="ShipCountry" placeholder="Vietnam">
					<br>
					<br>
				</fieldset>
				<input style="float: right; width: fit-content; padding: 5px; margin-top: 10px; background-color: forestgreen; color: white; cursor: pointer" type="submit" value="Add New Order">
			</form>
			@Model.Message <a asp-page="/Order/List" >Show Orders</a>
		</div>
	</div>
</body>

ExerciseRazerPage/ExerciseRazerPage/Pages/Order/List.cshtml
@page "{pageNumber?}"
@model ExerciseRazerPage.Pages.Order.ListModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
	<link rel="stylesheet" href="/css/styles.css" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
	<style>
		.orderList th, td {
			padding: 3px;
		}
		/* CSS */
		#back-to-top {
			position: fixed;
			bottom: 40px;
			right: 40px;
			z-index: 9999;
			text-align: center;
			line-height: 30px;
			background: #f5f5f5;
			color: indianred;
			cursor: pointer;
			border: 2px solid #ccc;
			border-radius: 15px;
			text-decoration: none;
			transition: opacity 3s ease-out;
			opacity: 0.85;
		}

			#back-to-top:hover {
				opacity: 1;
			}

		h3 {
			margin: 10px 0px;
		}

		.pagination {
			text-align: center;
			margin: 10px;
		}
	</style>
</head>
<body>
	<div style="display: flex; justify-content: space-between">
		<div style="height: 100vh; background-color: aliceblue; padding: 10px; position: fixed; top: 0; left: 0">
			<div><h2 style="text-align: center; background-color: bisque; width: 100%">FILTER</h2></div>
			<form method="post" id="form">
				<h3>Employee:</h3>
				<select name="EmployeeID" asp-for="EmployeeID"
						style="width: 100%; height: 30px">
					<option value="-1">All Employees</option>
					@if (Model.employees != null)
					{
						foreach (var e in Model.employees)
						{
							<option value="@e.EmployeeId">@e.FirstName @e.LastName</option>
						}
					}
				</select>
				<h3>Customer:</h3>
				<select name="CustomerID" asp-for="CustomerID"
						style="width: 100%; height: 30px">
					<option value="-1">All Customers</option>
					@if (Model.customers != null)
					{
						foreach (var e in Model.customers)
						{
							<option value="@e.CustomerId">@e.CompanyName</option>
						}
					}
				</select>
				<h3>From:</h3>
				<input type="date" name="FromDate" value="1980-01-01" style="width: 100%; height: 30px" />
				<h3>To:</h3>
				<input type="date" name="ToDate" value="@DateTime.Today.ToString("yyyy-MM-dd")" style="width: 100%; height: 30px" />
				<h3>Sort By:</h3>
				@switch (Model.SortBy)
				{
					case "OrderDate":
						<input type="radio" checked value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
					case "Freight":
						<input type="radio" value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" checked value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
					default:
						<input type="radio" checked value="OrderDate" name="SortBy" /> <label>Order Date</label>
						<br>
						<input type="radio" value="Freight" name="SortBy" /> <label>Freight</label>
						<br>
						break;
				}


				<input type="hidden" id="pageNumber" name="pageNumber">
				<input type="submit" value="Load Orders" style="margin-top: 15px; width: 100%; height: 30px; cursor: pointer" />
			</form>
		</div>
		<div style="padding: 0 10px 10px 10px; margin-left: 260px; border-left: 2px dashed #ccc">
			<div style="display: flex; justify-content: space-between">
				<div><h2>List of Order</h2></div>
				<div style="display: flex; align-items: center">
					<a href="/Order/Add">
						<button style="padding: 5px; background-color: forestgreen; color: white; cursor: pointer;">
							Add New Order
						</button>
					</a>
					@* <button type="submit" asp-page-handler="add" style="padding: 5px; background-color: forestgreen; color: white; cursor: pointer">
					Add New Order
					</button> *@
				</div>
			</div>
			<div style="display: flex; justify-content: center">
				@{
					if (Model.Orders.Count == 0)
					{
						<div>-- No Data --</div>
					}
					else
					{
						<table class="orderList" border="1px" style="border-collapse:collapse">
							<tr>
								<th>OrderID</th>
								<th>Customer</th>
								<th>Employee</th>
								<th>Order Date</th>
								<th>Required Date</th>
								<th>Shipped Date</th>
								<th>Freight</th>
								<th>Ship Country</th>
							</tr>
							@foreach (var o in Model.Orders)
							{
								<tr>
									<td>@o.OrderId</td>
									<td>@o.Customer.CompanyName</td>
									<td>@o.Employee.FirstName @o.Employee.LastName</td>
									<td>@o.OrderDate</td>
									<td>@o.RequiredDate</td>
									<td>@o.ShippedDate</td>
									<td>@o.Freight</td>
									<td>@o.ShipCountry</td>
								</tr>
							}
						</table>
					}
				}
			</div>
			<a href="#" id="back-to-top" style="display: none;padding: 5px;">
				<i style="text-align: center" class="fa fa-arrow-up"></i>
				<br />Back To Top</a>
			<div class="pagination">
				@for (int i = 1; i <= Model.TotalPages; i++)
				{
					@if (!Model.isFilter)
					{
						@if (Model.CurrentPageNumber == i)
						{
							<a style="cursor: pointer; margin:0 5px; color: red; font-weight: bold;
												text-decoration: none; border: 2px solid #ccc; line-height: 2;
												padding: 5px; border-radius: 7px; font-size: 18px" href="/Order/List/@i">@i</a>
						}else{
							<a style="cursor: pointer; margin: 0 5px; color: black; text-decoration: none; line-height: 2;" href="/Order/List/@i">@i</a>
						}
					}
					else
					{
						@if (Model.CurrentPageNumber == i)
						{
							<a href="#" style="cursor: pointer; margin:0 5px; color: red; font-weight: bold;
												text-decoration: none; border: 2px solid #ccc; line-height: 2;
												padding: 5px; border-radius: 7px; font-size: 18px" 
							onclick="OnClickPageNumberLink(@i)" id="pageNumberLink">@i</a>
						}
						else
						{
							<a href="#" style="cursor: pointer; margin: 0 5px; text-decoration: none; color: black; line-height: 2;"
							   onclick="OnClickPageNumberLink(@i)" id="pageNumberLink">@i</a>
						}
					}
				}
			</div>
		</div>
	</div>
	<script>
		// JavaScript
		$(document).ready(function () {
			$(window).scroll(function () {
				if ($(this).scrollTop() > 50) {
					$('#back-to-top').fadeIn();
				} else {
					$('#back-to-top').fadeOut();
				}
			});
			// scroll body to 0px on click
			$('#back-to-top').click(function () {
				$('body,html').animate({
					scrollTop: 0
				}, 400);
				return false;
			});
		});

	</script>
	<script>
		function OnClickPageNumberLink(i) {
			console.log("pageNumber = " + i);
			document.getElementById('pageNumber').value = i;
			document.getElementById('form').submit();
		}
	</script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>